Repository AY2021S1-CS2103T-W13-3/tp, pull requests merged in 2020-11, with the labels that each got.

#298 Fix bugs
  .github/workflows/gradle.yml
  docs/UserGuide.md
  src/main/java/seedu/homerce/commons/core/GuiSettings.java
  src/main/java/seedu/homerce/model/expense/predicate/ExpenseDescriptionPredicate.java
  src/main/java/seedu/homerce/ui/MainWindow.java
  src/main/java/seedu/homerce/ui/financialpanel/FinanceWindow.java
  src/main/resources/view/financialpanel/BreakdownFinancial.fxml
  src/main/resources/view/financialpanel/style.css
  src/test/java/seedu/homerce/model/expense/ExpenseDescriptionPredicateTest.java
Labels: priority.High, type.Bug

#299 Update findcli command
  src/main/java/seedu/homerce/logic/parser/client/FindClientCommandParser.java
  src/main/java/seedu/homerce/model/client/predicate/ClientNamePredicate.java
  src/main/java/seedu/homerce/model/client/predicate/ClientPhonePredicate.java
  src/main/java/seedu/homerce/model/client/predicate/NameContainsKeywordsPredicate.java
  src/test/java/seedu/homerce/logic/commands/CommandTestUtil.java
  src/test/java/seedu/homerce/logic/commands/client/FindClientCommandTest.java
  src/test/java/seedu/homerce/logic/parser/client/FindClientCommandParserTest.java
  src/test/java/seedu/homerce/model/ModelManagerTest.java
  src/test/java/seedu/homerce/model/client/predicate/ClientNamePredicateTest.java
  src/test/java/seedu/homerce/model/client/predicate/NameContainsKeywordsPredicateTest.java
Labels: priority.High, severity.High, type.Bug

#296 Update deletecli and edit client behaviour
  src/main/java/seedu/homerce/commons/core/Messages.java
  src/main/java/seedu/homerce/logic/commands/client/DeleteClientCommand.java
  src/main/java/seedu/homerce/logic/commands/client/EditClientCommand.java
  src/main/java/seedu/homerce/model/ModelManager.java
  src/main/java/seedu/homerce/model/appointment/Appointment.java
  src/main/java/seedu/homerce/model/appointment/uniquelist/UniqueAppointmentList.java
  src/main/java/seedu/homerce/model/manager/AppointmentManager.java
  src/test/data/Client/JsonSerializableClientManagerTest/typicalClientManager.json
  src/test/java/seedu/homerce/logic/commands/client/DeleteClientCommandTest.java
  src/test/java/seedu/homerce/model/manager/AppointmentManagerTest.java
  src/test/java/seedu/homerce/testutil/appointment/TypicalAppointments.java
Labels: severity.High, type.Bug

#301 Add GUI Screenshots for UG (Expense & Breakdown Finance)
  docs/UserGuide.md
  docs/images/addexp.png
  docs/images/breakdownfinance.png
  docs/images/clearexp.png
  docs/images/deleteexp.png
  docs/images/editexp.png
  docs/images/findexp.png
  docs/images/listexp.png
  docs/images/sortexp.png
Labels: documentation

#303 Change findsvc implementation
  docs/UserGuide.md
  docs/diagrams/CommitActivityDiagram.png
  docs/diagrams/DeleteSequenceDiagram.png
  docs/diagrams/UndoRedoState0.png
  docs/diagrams/UndoRedoState1.png
  docs/diagrams/UndoRedoState2.png
  docs/diagrams/UndoRedoState3.png
  docs/diagrams/UndoRedoState4.png
  docs/diagrams/UndoRedoState5.png
  docs/diagrams/UndoSequenceDiagram.png
  src/main/java/seedu/homerce/logic/commands/service/DeleteServiceCommand.java
  src/main/java/seedu/homerce/logic/commands/service/FindServiceCommand.java
  src/main/java/seedu/homerce/logic/parser/service/DeleteServiceCommandParser.java
  src/main/java/seedu/homerce/logic/parser/service/FindServiceCommandParser.java
  src/main/java/seedu/homerce/model/service/ServiceCodeGenerator.java
  src/main/java/seedu/homerce/model/service/predicate/ServiceCodePredicate.java
  src/main/java/seedu/homerce/model/service/predicate/ServiceTitlePredicate.java
  src/main/java/seedu/homerce/ui/MainWindow.java
Labels: priority.High, severity.High, type.Bug

#304 Amount and Duration bug fixes
  src/main/java/seedu/homerce/logic/commands/expense/AddExpenseCommand.java
  src/main/java/seedu/homerce/logic/parser/ParserUtil.java
  src/main/java/seedu/homerce/model/service/Duration.java
  src/main/java/seedu/homerce/model/util/attributes/Amount.java
Labels: priority.High, severity.Low, type.Bug

#306 Change behavior of edit commands for all list managers.
  src/main/java/seedu/homerce/logic/commands/appointment/DoneAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/EditAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/UnDoneAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/client/EditClientCommand.java
  src/main/java/seedu/homerce/logic/commands/expense/EditExpenseCommand.java
  src/main/java/seedu/homerce/logic/commands/service/EditServiceCommand.java
  src/test/java/seedu/homerce/logic/commands/client/EditClientCommandTest.java
  src/test/java/seedu/homerce/logic/commands/service/EditServiceCommandTest.java
Labels: priority.Low, type.Bug

#309 Scale GUI Window
  docs/team/yanlynnnnn.md
  src/main/java/seedu/homerce/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, type.Bug

#307 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/appointment/DoneAppointmentActivityDiagram.puml
  docs/diagrams/appointment/DoneAppointmentSequenceDiagram.puml
  docs/diagrams/client/FindClientSequenceDiagram.puml
  docs/diagrams/design/BetterModelClassDiagram.puml
  docs/diagrams/design/LogicClassDiagram.puml
  docs/diagrams/design/ModelClassDiagram.puml
  docs/diagrams/design/StorageClassDiagram.puml
  docs/diagrams/design/UiClassDiagram.puml
  docs/diagrams/expense/SortExpenseSD.puml
  docs/diagrams/financebreakdown/BreakdownFinanceSequenceDiagram.puml
  docs/diagrams/service/AddServiceSequenceDiagram.puml
  docs/images/AddServiceSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/BreakdownFinanceSequenceDiagram.png
  docs/images/DoneAppointmentActivityDiagram.png
  docs/images/DoneAppointmentSequenceDiagram.png
  docs/images/FindClientSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/SortExpenseSD.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/request_access.png
  docs/index.md
  src/main/java/seedu/homerce/logic/commands/appointment/DoneAppointmentCommand.java
Labels: documentation, priority.High

#310 Update Quick Start in UG
  docs/UserGuide.md
  docs/diagrams/expense/SortExpenseActivityDiagram.puml
  docs/images/SortExpenseActivityDiagram.png
Labels: type.Bug

#305 Fix service bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/service/AddServiceSequenceDiagram.puml
  src/main/java/seedu/homerce/logic/commands/schedule/CurrentWeekCommand.java
  src/main/java/seedu/homerce/logic/commands/service/AddServiceCommand.java
  src/main/java/seedu/homerce/logic/commands/service/ClearServiceCommand.java
  src/main/java/seedu/homerce/logic/commands/service/DeleteServiceCommand.java
  src/main/java/seedu/homerce/model/service/ServiceCodeGenerator.java
  src/main/java/seedu/homerce/ui/HelpWindow.java
  src/test/java/seedu/homerce/logic/commands/service/AddServiceCommandTest.java
  src/test/java/seedu/homerce/model/service/ServiceCodeGeneratorTest.java
Labels: priority.High, severity.High, type.Bug

#313 Documentation v1.4
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/appointment/DoneAppointmentSequenceDiagram.puml
  docs/diagrams/client/FindClientSequenceDiagram.puml
  docs/diagrams/expense/SortExpenseSD.puml
  docs/diagrams/financebreakdown/BreakdownFinanceSequenceDiagram.puml
  docs/diagrams/revenue/ClearRevenueActivityDiagram.puml
  docs/diagrams/revenue/ClearRevenueSD.puml
  docs/diagrams/revenue/SortRevenueActivityDiagram.puml
  docs/diagrams/revenue/SortRevenueSD.puml
  docs/diagrams/service/AddServiceSequenceDiagram.puml
  docs/images/AddServiceSequenceDiagram.png
  docs/images/AnnotatedUI.png
  docs/images/BreakdownFinanceSequenceDiagram.png
  docs/images/DoneAppointmentSequenceDiagram.png
  docs/images/FindClientSequenceDiagram.png
  docs/images/SortExpenseSD.png
  docs/images/revenue/ClearRevenue.png
  docs/images/revenue/ClearRevenueActivityDiagram.png
  docs/images/revenue/ClearRevenueSD.png
  docs/images/revenue/FindRevenue.png
  docs/images/revenue/ListRevenue.png
  docs/images/revenue/SortRevenue(Desc).png
  docs/images/revenue/SortRevenueActivityDiagram.png
  docs/images/revenue/SortRevenueSD.png
  src/main/java/seedu/homerce/commons/core/Messages.java
  src/main/java/seedu/homerce/logic/commands/ExitCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/DoneAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/revenue/FindRevenueCommand.java
  src/main/java/seedu/homerce/logic/commands/revenue/SortRevenueCommand.java
  src/main/java/seedu/homerce/logic/parser/ParserUtil.java
  src/main/java/seedu/homerce/model/Model.java
  src/main/java/seedu/homerce/model/ModelManager.java
  src/main/java/seedu/homerce/model/manager/RevenueTracker.java
  src/main/java/seedu/homerce/model/revenue/predicate/RevenueMonthYearPredicate.java
  src/test/java/seedu/homerce/logic/commands/client/AddClientCommandTest.java
Labels: documentation, priority.High, type.Bug

#315 Add screenshots for Client
  docs/UserGuide.md
  docs/images/addcli.png
  docs/images/addexp.png
  docs/images/clearcli.png
  docs/images/clearexp.png
  docs/images/deletecli.png
  docs/images/deleteexp.png
  docs/images/editcli.png
  docs/images/editexp.png
  docs/images/findcli.png
  docs/images/findexp.png
  docs/images/listcli.png
  docs/images/listexp.png
  docs/images/sortexp.png
  src/main/java/seedu/homerce/logic/commands/client/ClearClientCommand.java
  src/main/resources/view/schedulepanel/SchedulePanel.fxml
Labels: documentation

#317 Documentation v1.4
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/galvinleow.md
Labels: documentation, priority.Medium

#318 Add warnings and tips for delete and find client command
  docs/UserGuide.md
  docs/team/yanlynnnnn.md
  src/main/java/seedu/homerce/logic/commands/client/FindClientCommand.java
Labels: documentation, priority.High

#320 yanlyn's PPP
  docs/team/galvinleow.md
  docs/team/yanlynnnnn.md
Labels: documentation, type.Task

#322 Documentation v1.4
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/revenue/ClearRevenueSD.puml
  docs/images/revenue/ClearRevenueSD.png
  docs/team/galvinleow.md
Labels: documentation, priority.High, type.Bug

#314 Update DG
  README.md
  docs/DeveloperGuide.md
  docs/diagrams/CommitActivityDiagram.png
  docs/diagrams/DeleteSequenceDiagram.png
  docs/diagrams/UndoRedoState0.png
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.png
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.png
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.png
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.png
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.png
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.png
  docs/diagrams/undo/CommitActivityDiagram.puml
  docs/diagrams/undo/UndoSequenceDiagram.puml
  docs/diagrams/undo/UndoState0.puml
  docs/diagrams/undo/UndoState1.puml
  docs/diagrams/undo/UndoState2.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/UndoState0.png
  docs/images/UndoState1.png
  docs/images/UndoState2.png
Labels: documentation, priority.High

#324 Add screenshot to UG
  docs/UserGuide.md
  docs/images/addsvc.png
  docs/images/clearsvc.png
  docs/images/deletesvc.png
  docs/images/editsvc.png
  docs/images/findsvc.png
  docs/images/listsvc.png
  docs/images/undo.png
  src/main/java/seedu/homerce/logic/commands/appointment/ClearAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/client/ClearClientCommand.java
  src/main/java/seedu/homerce/logic/commands/expense/ClearExpenseCommand.java
  src/main/java/seedu/homerce/logic/commands/revenue/ClearRevenueCommand.java
  src/main/java/seedu/homerce/logic/commands/schedule/CurrentWeekCommand.java
  src/main/java/seedu/homerce/logic/commands/service/ClearServiceCommand.java
Labels: documentation, priority.High, type.Bug

#325 Update PPP Hans' PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/service/AddServiceActivityDiagram.png
  docs/images/service/AddServiceSequenceDiagram.png
  docs/team/hansebastian.md
Labels: documentation, priority.High

#326 Update UG for future enhancements
  docs/UserGuide.md
  docs/images/breakdownfinance.png
  docs/team/yanlynnnnn.md
  src/main/java/seedu/homerce/model/expense/IsFixed.java
  src/main/java/seedu/homerce/model/util/attributes/Date.java
  src/main/java/seedu/homerce/model/util/attributes/Description.java
Labels: documentation, priority.High

#328 Update DG with deletecli information
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/client/DeleteClientActivityDiagram.puml
  docs/diagrams/client/DeleteClientSequenceDiagram.puml
  docs/diagrams/client/FindClientSequenceDiagram.puml
  docs/images/DeleteClientActivityDiagram.png
  docs/images/DeleteClientSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/FindClientSequenceDiagram.png
  docs/team/ruifengg.md
Labels: documentation, priority.High

#319 Bug Fixes for Appointment
  docs/UserGuide.md
  src/main/java/seedu/homerce/logic/commands/appointment/AddAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/DoneAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/UnDoneAppointmentCommand.java
  src/main/java/seedu/homerce/model/Model.java
  src/main/java/seedu/homerce/model/appointment/TimeOfDay.java
  src/main/java/seedu/homerce/model/manager/ClientManager.java
  src/main/java/seedu/homerce/model/manager/ReadOnlyAppointmentManager.java
  src/main/java/seedu/homerce/model/manager/ServiceManager.java
  src/main/java/seedu/homerce/ui/HelpWindow.java
  src/test/java/seedu/homerce/logic/commands/appointment/AddAppointmentCommandTest.java
  src/test/java/seedu/homerce/logic/commands/client/AddClientCommandTest.java
  src/test/java/seedu/homerce/logic/commands/expense/AddExpenseCommandTest.java
  src/test/java/seedu/homerce/logic/commands/revenue/AddRevenueCommandTest.java
  src/test/java/seedu/homerce/logic/commands/service/AddServiceCommandTest.java
  src/test/java/seedu/homerce/model/appointment/TimeOfDayTest.java
  src/test/java/seedu/homerce/testutil/ModelStub.java
Labels: priority.High, type.Bug

#329 Ruifeng's PPP
  docs/team/ruifengg.md
Labels: documentation

#330 Update UG, DG & PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/addapt.png
  docs/images/clearapt.png
  docs/images/deleteapt.png
  docs/images/doneapt.png
  docs/images/editapt.png
  docs/images/findapt.png
  docs/images/listapt.png
  docs/images/undoneapt.png
  docs/team/khoongwk.md
Labels: documentation, priority.High

#323 Documentation v1.4
  docs/UserGuide.md
  docs/team/galvinleow.md
  src/main/java/seedu/homerce/logic/parser/HomerceParser.java
  src/main/java/seedu/homerce/model/manager/RevenueTracker.java
  src/main/java/seedu/homerce/model/revenue/RevenueComparator.java
Labels: priority.High

#333 Fix findapt by name and Ui Tab Navigation.
  src/main/java/seedu/homerce/logic/commands/appointment/DeleteAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/DoneAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/EditAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/FindAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/UnDoneAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/expense/DeleteExpenseCommand.java
  src/main/java/seedu/homerce/logic/commands/expense/EditExpenseCommand.java
  src/main/java/seedu/homerce/logic/commands/revenue/DeleteRevenueCommand.java
  src/main/java/seedu/homerce/logic/commands/service/DeleteServiceCommand.java
  src/main/java/seedu/homerce/logic/commands/service/EditServiceCommand.java
  src/main/java/seedu/homerce/logic/parser/appointment/FindAppointmentCommandParser.java
  src/main/java/seedu/homerce/model/appointment/predicate/AppointmentNamePredicate.java
  src/test/java/seedu/homerce/logic/parser/appointment/FindAppointmentCommandParserTest.java
  src/test/java/seedu/homerce/model/appointment/predicate/AppointmentNamePredicateTest.java
Labels: priority.Medium, type.Bug

#334 Update sample data for appointments
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/galvinleow.md
  docs/team/hansebastian.md
  docs/team/khoongwk.md
  docs/team/ruifengg.md
  docs/team/yanlynnnnn.md
  src/main/java/seedu/homerce/model/util/SampleDataUtil.java
Labels: priority.High, type.Task

#336 Change PPP to bullet points
  docs/team/khoongwk.md
Labels: documentation, priority.Medium

#337 Update figure numbering in DG
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#335 Reorder features in UG
  docs/UserGuide.md
Labels: documentation, priority.High

#341 Include diagrams for UG schedule
  docs/UserGuide.md
  docs/images/findsvc.png
  docs/images/nextweek.png
  docs/images/previousweek.png
  docs/images/schedule.png
Labels: documentation, priority.High

#354 Bunch of Bug Fixes for Appointment
  docs/UserGuide.md
  docs/team/khoongwk.md
  src/main/java/seedu/homerce/commons/core/Messages.java
  src/main/java/seedu/homerce/logic/commands/appointment/AddAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/EditAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/client/EditClientCommand.java
  src/main/java/seedu/homerce/logic/commands/expense/EditExpenseCommand.java
  src/main/java/seedu/homerce/logic/commands/service/EditServiceCommand.java
  src/main/java/seedu/homerce/logic/parser/appointment/EditAppointmentCommandParser.java
  src/main/java/seedu/homerce/logic/parser/client/EditClientCommandParser.java
  src/main/java/seedu/homerce/logic/parser/expense/EditExpenseCommandParser.java
  src/main/java/seedu/homerce/logic/parser/service/EditServiceCommandParser.java
  src/main/java/seedu/homerce/ui/appointmentpanel/AppointmentCard.java
  src/test/java/seedu/homerce/logic/commands/appointment/EditAppointmentCommandTest.java
  src/test/java/seedu/homerce/logic/commands/client/EditClientCommandTest.java
  src/test/java/seedu/homerce/logic/commands/expense/EditExpenseCommandTest.java
  src/test/java/seedu/homerce/logic/commands/service/EditServiceCommandTest.java
  src/test/java/seedu/homerce/logic/parser/appointment/EditAppointmentCommandParserTest.java
  src/test/java/seedu/homerce/logic/parser/client/EditClientCommandParserTest.java
Labels: documentation, priority.High, type.Bug

#357 Update UG Screenshots
  docs/images/addapt.png
  docs/images/addsvc.png
  docs/images/clearapt.png
  docs/images/deleteapt.png
  docs/images/deletesvc.png
  docs/images/doneapt.png
  docs/images/editapt.png
  docs/images/editsvc.png
  docs/images/findapt.png
  docs/images/listapt.png
  docs/images/listsvc.png
  docs/images/undoneapt.png
Labels: documentation, priority.High

#358 Update sequence diagram for AddServiceCommand in DG
  docs/UserGuide.md
  docs/diagrams/service/AddServiceSequenceDiagram.puml
  docs/images/service/AddServiceSequenceDiagram.png
Labels: documentation, priority.High

#363 Important Fixes for Client
  docs/tutorials/TracingCode.md
  src/main/java/seedu/homerce/logic/commands/client/AddClientCommand.java
  src/main/java/seedu/homerce/logic/commands/client/EditClientCommand.java
  src/main/java/seedu/homerce/model/client/Client.java
  src/main/java/seedu/homerce/model/client/UniqueClientList.java
  src/main/java/seedu/homerce/model/client/exceptions/DuplicateClientException.java
  src/main/java/seedu/homerce/model/manager/AppointmentManager.java
  src/main/java/seedu/homerce/model/manager/ClientManager.java
  src/test/java/seedu/homerce/logic/commands/client/AddClientCommandTest.java
  src/test/java/seedu/homerce/model/client/ClientTest.java
  src/test/java/seedu/homerce/model/client/UniqueClientListTest.java
  src/test/java/seedu/homerce/model/manager/ClientManagerTest.java
Labels: priority.High, type.Bug

#361 Update UG Screenshots and Examples for Client
  docs/UserGuide.md
  docs/images/deletecli.png
  docs/images/findcli.png
  docs/images/listcli.png
  docs/team/yanlynnnnn.md
Labels: documentation, priority.High

#360 Fix DG related bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/client/DeleteClientSequenceDiagram.puml
  docs/diagrams/design/ArchitectureSequenceDiagram.puml
  docs/diagrams/design/BetterModelClassDiagram.puml
  docs/diagrams/design/ModelClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteClientSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  src/main/java/seedu/homerce/ui/CommandBox.java
  src/main/java/seedu/homerce/ui/MainWindow.java
Labels: documentation, type.Bug

#359 Documentation v1.4
  SortExpenseActivityDiagram.png
  docs/AboutUs.md
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/galvinleow.md
Labels: documentation, priority.High

#364 Fix UG bugs
  docs/UserGuide.md
  docs/team/ruifengg.md
  src/main/java/seedu/homerce/model/appointment/predicate/AppointmentPhonePredicate.java
  src/main/java/seedu/homerce/ui/CommandBox.java
  src/main/java/seedu/homerce/ui/MainWindow.java
Labels: documentation, type.Bug

#365 Sort Revenue Command Unit Test
  docs/team/galvinleow.md
  src/main/java/seedu/homerce/logic/commands/UndoCommand.java
  src/main/java/seedu/homerce/logic/commands/revenue/SortRevenueCommand.java
  src/test/java/seedu/homerce/logic/commands/revenue/SortRevenueCommandTest.java
  src/test/java/seedu/homerce/logic/parser/revenue/SortRevenueCommandParserTest.java
Labels: type:Testing

#367 Bug fixes and documentation enhancements
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/hansebastian.md
  src/main/java/seedu/homerce/commons/core/Messages.java
  src/main/java/seedu/homerce/logic/commands/UndoCommand.java
  src/main/java/seedu/homerce/logic/commands/service/AddServiceCommand.java
  src/main/java/seedu/homerce/logic/commands/service/EditServiceCommand.java
  src/main/java/seedu/homerce/logic/parser/ParserUtil.java
  src/main/java/seedu/homerce/model/manager/ServiceManager.java
  src/main/java/seedu/homerce/model/service/Service.java
  src/main/java/seedu/homerce/model/util/attributes/Amount.java
  src/test/java/seedu/homerce/logic/commands/service/AddServiceCommandIntegrationTest.java
  src/test/java/seedu/homerce/logic/commands/service/EditServiceCommandTest.java
  src/test/java/seedu/homerce/logic/parser/expense/EditExpenseCommandParserTest.java
Labels: documentation, priority.High, type.Bug

#368 add valid date for expense
  docs/UserGuide.md
  docs/team/yanlynnnnn.md
Labels: documentation

#369 Documentation v1.4
  docs/team/galvinleow.md
Labels: documentation, priority.Low

#371 Some bug fixes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/homerce/logic/commands/appointment/AddAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/service/AddServiceCommand.java
  src/main/java/seedu/homerce/model/service/Duration.java
Labels: documentation, priority.High, type.Bug

#372 Add schedule view feature into DG
  docs/DeveloperGuide.md
  docs/team/ruifengg.md
Labels: documentation

#373 Include Object UML diagram for schedule view in DG
  ScheduleObjectDiagram.png
  docs/DeveloperGuide.md
  docs/diagrams/schedule/ScheduleObjectDiagram.puml
  docs/images/ScheduleObjectDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
  docs/team/hansebastian.md
  src/main/java/seedu/homerce/logic/parser/ParserUtil.java
  src/main/java/seedu/homerce/model/manager/ServiceManager.java
  src/main/java/seedu/homerce/ui/schedulepanel/SchedulePanel.java
Labels: documentation, priority.High
