Repository AY2021S1-CS2103T-W13-3/tp, pull requests merged in 2020-10, with the labels that each got.

#51 Add tests for shared attribute classes
  src/main/java/seedu/address/model/util/attributes/Description.java
  src/test/java/seedu/address/model/util/attributes/AmountTest.java
  src/test/java/seedu/address/model/util/attributes/DateTest.java
  src/test/java/seedu/address/model/util/attributes/DescriptionTest.java
  src/test/java/seedu/address/model/util/attributes/TagTest.java
Labels: priority.High, type.Task

#64 Update User Guide for Revenue
  docs/UserGuide.md
Labels: documentation, priority.High

#72 Update User Guide for Appointment Command
  docs/UserGuide.md
Labels: documentation, priority.High

#62 Update UG for Service functionality
  docs/UserGuide.md
  docs/diagrams/ArchitectureDiagram.puml
  src/main/resources/view/HelpWindow.fxml
Labels: documentation, priority.High

#75 Update Appointment Classes
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/Time.java
  src/main/java/seedu/address/model/service/Service.java
Labels: priority.High, type.Task

#73 Update DG - Overall Structure, Product Scope, NFR
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#68 Update Expense Feature
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddModuleCommand.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/expense/AddExpenseCommand.java
  src/main/java/seedu/address/logic/commands/expense/ClearExpenseCommand.java
  src/main/java/seedu/address/logic/commands/expense/DeleteExpenseCommand.java
  src/main/java/seedu/address/logic/commands/expense/EditExpenseCommand.java
  src/main/java/seedu/address/logic/commands/expense/FindExpenseCommand.java
  src/main/java/seedu/address/logic/commands/expense/ListExpenseCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/expense/AddExpenseCommandParser.java
  src/main/java/seedu/address/logic/parser/expense/DeleteExpenseCommandParser.java
  src/main/java/seedu/address/logic/parser/expense/EditExpenseCommandParser.java
  src/main/java/seedu/address/logic/parser/expense/FindExpenseCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/expense/DatePredicate.java
  src/main/java/seedu/address/model/expense/DescriptionPredicate.java
  src/main/java/seedu/address/model/expense/Expense.java
  src/main/java/seedu/address/model/expense/ExpenseList.java
  src/main/java/seedu/address/model/expense/IsFixed.java
  src/main/java/seedu/address/model/expense/IsFixedPredicate.java
  src/main/java/seedu/address/model/expense/TagPredicate.java
  src/main/java/seedu/address/model/expense/exceptions/ExpenseNotFoundException.java
  src/main/java/seedu/address/model/revenue/Revenue.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.High

#88 Add Service Functionality
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/expense/AddExpenseCommand.java
  src/main/java/seedu/address/logic/commands/service/AddServiceCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/service/AddServiceCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/manager/ReadOnlyServiceManager.java
  src/main/java/seedu/address/model/manager/ServiceManager.java
  src/main/java/seedu/address/model/service/Duration.java
  src/main/java/seedu/address/model/service/Service.java
  src/main/java/seedu/address/model/service/ServiceCode.java
  src/main/java/seedu/address/model/service/exceptions/MaximumServiceException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/model/util/attributes/Price.java
  src/main/java/seedu/address/model/util/attributes/Title.java
  src/main/java/seedu/address/model/util/uniquelist/UniqueList.java
  src/main/java/seedu/address/model/util/uniquelist/UniqueListItem.java
  src/main/java/seedu/address/model/util/uniquelist/exceptions/DuplicateItemException.java
  src/main/java/seedu/address/model/util/uniquelist/exceptions/ItemNotFoundException.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/service/JsonAdaptedService.java
  src/main/java/seedu/address/storage/service/JsonSerializableServiceManager.java
  src/main/java/seedu/address/storage/service/JsonServiceStorage.java
  src/main/java/seedu/address/storage/service/ServiceStorage.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/servicetab/ServiceCard.java
  src/main/java/seedu/address/ui/servicetab/ServiceListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.High, type.Story

#91 Refactor code to merge Price and Amount classes
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/service/AddServiceCommandParser.java
  src/main/java/seedu/address/model/service/Service.java
  src/main/java/seedu/address/model/service/ServiceCode.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/model/util/attributes/Amount.java
  src/main/java/seedu/address/model/util/attributes/Price.java
  src/main/java/seedu/address/storage/service/JsonAdaptedService.java
  src/main/java/seedu/address/ui/servicetab/ServiceCard.java
  src/test/java/seedu/address/model/util/attributes/AmountTest.java
Labels: priority.High, type.Task

#94 Add Service editing feature
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/expense/EditExpenseCommand.java
  src/main/java/seedu/address/logic/commands/service/EditServiceCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/service/EditServiceCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, type.Story

#95 Add Service deletion functionality
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/service/DeleteServiceCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/service/DeleteServiceCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, type.Story

#103 List services logic
  src/main/java/seedu/address/logic/commands/service/ListServiceCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: priority.High, type.Task

#104 Clear services functionality
  src/main/java/seedu/address/logic/commands/service/ClearServiceCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, type.Story

#110 Update client command names
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/client/AddClientCommand.java
  src/main/java/seedu/address/logic/commands/client/ClearClientCommand.java
  src/main/java/seedu/address/logic/commands/client/DeleteClientCommand.java
  src/main/java/seedu/address/logic/commands/client/EditClientCommand.java
  src/main/java/seedu/address/logic/commands/client/FindClientCommand.java
  src/main/java/seedu/address/logic/commands/client/ListClientCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/service/DeleteServiceCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/client/AddClientCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/client/AddClientCommandTest.java
  src/test/java/seedu/address/logic/commands/client/ClearClientCommandTest.java
  src/test/java/seedu/address/logic/commands/client/DeleteClientCommandTest.java
  src/test/java/seedu/address/logic/commands/client/EditClientCommandTest.java
  src/test/java/seedu/address/logic/commands/client/EditClientDescriptorTest.java
  src/test/java/seedu/address/logic/commands/client/FindClientCommandTest.java
  src/test/java/seedu/address/logic/commands/client/ListClientCommandTest.java
  src/test/java/seedu/address/logic/parser/AddClientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteClientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditClientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindClientCommandParserTest.java
  src/test/java/seedu/address/testutil/ClientUtil.java
  src/test/java/seedu/address/testutil/EditClientDescriptorBuilder.java
Labels: priority.High, type.Task

#123 Repackage client classes
  docs/tutorials/AddRemark.md
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/client/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/client/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/client/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/client/FindCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/clientspanel/ClientCard.java
  src/main/java/seedu/address/ui/clientspanel/ClientListPanel.java
  src/main/java/seedu/address/ui/servicepanel/ServiceCard.java
  src/main/java/seedu/address/ui/servicepanel/ServiceListPanel.java
  src/main/resources/view/clientspanel/ClientListCard.fxml
  src/main/resources/view/clientspanel/ClientListPanel.fxml
  src/test/java/seedu/address/logic/parser/client/AddClientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/client/DeleteClientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/client/EditClientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/client/FindClientCommandParserTest.java
Labels: priority.High

#105 Find service functionality
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/expense/FindExpenseCommand.java
  src/main/java/seedu/address/logic/commands/service/FindServiceCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/service/FindServiceCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/service/ServiceCodePredicate.java
  src/main/java/seedu/address/model/service/ServiceContainKeywordPredicate.java
  src/main/java/seedu/address/model/service/ServiceTitlePredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/expense/JsonAdaptedExpense.java
  src/main/java/seedu/address/storage/expense/JsonExpenseStorage.java
  src/main/java/seedu/address/storage/expense/JsonSerializableExpenseTracker.java
  src/test/java/seedu/address/model/util/attributes/DateTest.java
Labels: priority.High, type.Story

#90 Developer guide v1.2
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#125 Fix Storage Bug, Add checks for FindExpenseCommand, Refactor isFixed user input
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/expense/ClearExpenseCommand.java
  src/main/java/seedu/address/logic/commands/expense/FindExpenseCommand.java
  src/main/java/seedu/address/logic/parser/expense/FindExpenseCommandParser.java
  src/main/java/seedu/address/model/expense/IsFixed.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/model/util/attributes/Amount.java
  src/main/java/seedu/address/storage/expense/JsonAdaptedExpense.java
  src/main/java/seedu/address/storage/expense/JsonSerializableExpenseTracker.java
  src/test/java/seedu/address/model/util/attributes/DateTest.java
Labels: priority.High

#134 Add Expense Panel, Change implementation for ClearExpandCommand execu…
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/expense/ClearExpenseCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/expensepanel/ExpenseCard.java
  src/main/java/seedu/address/ui/expensepanel/ExpenseListPanel.java
  src/test/java/seedu/address/logic/commands/client/AddClientCommandTest.java
Labels: hacktoberfest-accepted, priority.High

#137 Link all components to panel UI
  docs/DeveloperGuide.md
  docs/team/hansebastian.md
  docs/tutorials/AddRemark.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/Panel.java
  src/main/java/seedu/address/ui/SideTabsBar.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/java/seedu/address/ui/appointmentpanel/AppointmentCard.java
  src/main/java/seedu/address/ui/appointmentpanel/AppointmentListPanel.java
  src/main/java/seedu/address/ui/clientpanel/ClientCard.java
  src/main/java/seedu/address/ui/clientpanel/ClientListPanel.java
  src/main/java/seedu/address/ui/expensepanel/ExpenseCard.java
  src/main/java/seedu/address/ui/expensepanel/ExpenseListPanel.java
  src/main/java/seedu/address/ui/revenuepanel/RevenueCard.java
  src/main/java/seedu/address/ui/revenuepanel/RevenueListPanel.java
  src/main/java/seedu/address/ui/servicepanel/ServiceCard.java
  src/main/java/seedu/address/ui/servicepanel/ServiceListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/SideTabsBar.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/main/resources/view/TabPanel.fxml
  src/main/resources/view/appointmentpanel/AppointmentListCard.fxml
  src/main/resources/view/appointmentpanel/AppointmentListPanel.fxml
  src/main/resources/view/clientpanel/ClientListCard.fxml
  src/main/resources/view/clientpanel/ClientListPanel.fxml
  src/main/resources/view/expensepanel/ExpenseListCard.fxml
  src/main/resources/view/expensepanel/ExpenseListPanel.fxml
  src/main/resources/view/revenuepanel/RevenueListCard.fxml
  src/main/resources/view/revenuepanel/RevenueListPanel.fxml
  src/main/resources/view/servicepanel/ServiceListCard.fxml
  src/main/resources/view/servicepanel/ServiceListPanel.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/client/JsonClientManagerStorageTest.java
  src/test/java/seedu/address/storage/client/JsonSerializableClientManagerTest.java
Labels: hacktoberfest-accepted, priority.High, type.Enhancement

#150 Add service code generator
  src/main/java/seedu/homerce/logic/commands/service/AddServiceCommand.java
  src/main/java/seedu/homerce/model/service/ServiceCode.java
  src/main/java/seedu/homerce/model/util/attributes/service/ServiceCodeGenerator.java
Labels: priority.High, type.Task

#147 Profit command feature
  src/main/java/seedu/homerce/logic/commands/ProfitCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/AddAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/EditAppointmentCommand.java
  src/main/java/seedu/homerce/logic/parser/CliSyntax.java
  src/main/java/seedu/homerce/logic/parser/HomerceParser.java
  src/main/java/seedu/homerce/logic/parser/ParserUtil.java
  src/main/java/seedu/homerce/logic/parser/ProfitCommandParser.java
  src/main/java/seedu/homerce/logic/parser/appointment/FindAppointmentCommandParser.java
  src/main/java/seedu/homerce/logic/parser/client/FindClientCommandParser.java
  src/main/java/seedu/homerce/logic/parser/expense/FindExpenseCommandParser.java
  src/main/java/seedu/homerce/logic/parser/revenue/FindRevenueCommandParser.java
  src/main/java/seedu/homerce/logic/parser/service/FindServiceCommandParser.java
  src/main/java/seedu/homerce/model/Model.java
  src/main/java/seedu/homerce/model/ModelManager.java
  src/main/java/seedu/homerce/model/appointment/predicate/AppointmentDatePredicate.java
  src/main/java/seedu/homerce/model/appointment/predicate/AppointmentNamePredicate.java
  src/main/java/seedu/homerce/model/appointment/predicate/AppointmentPhonePredicate.java
  src/main/java/seedu/homerce/model/appointment/predicate/AppointmentServiceCodePredicate.java
  src/main/java/seedu/homerce/model/client/Phone.java
  src/main/java/seedu/homerce/model/client/predicate/ClientNamePredicate.java
  src/main/java/seedu/homerce/model/client/predicate/ClientPhonePredicate.java
  src/main/java/seedu/homerce/model/client/predicate/NameContainsKeywordsPredicate.java
  src/main/java/seedu/homerce/model/expense/predicate/ExpenseDatePredicate.java
  src/main/java/seedu/homerce/model/expense/predicate/ExpenseDescriptionPredicate.java
  src/main/java/seedu/homerce/model/expense/predicate/ExpenseIsFixedPredicate.java
  src/main/java/seedu/homerce/model/expense/predicate/ExpenseMonthPredicate.java
  src/main/java/seedu/homerce/model/expense/predicate/ExpenseYearPredicate.java
  src/main/java/seedu/homerce/model/manager/ClientManager.java
  src/main/java/seedu/homerce/model/manager/ExpenseTracker.java
  src/main/java/seedu/homerce/model/manager/RevenueTracker.java
  src/main/java/seedu/homerce/model/revenue/predicate/RevenueDatePredicate.java
  src/main/java/seedu/homerce/model/revenue/predicate/RevenueMonthPredicate.java
  src/main/java/seedu/homerce/model/revenue/predicate/RevenueServiceCodePredicate.java
  src/main/java/seedu/homerce/model/revenue/predicate/RevenueYearPredicate.java
  src/main/java/seedu/homerce/model/service/predicate/ServiceCodePredicate.java
  src/main/java/seedu/homerce/model/service/predicate/ServiceContainKeywordPredicate.java
  src/main/java/seedu/homerce/model/service/predicate/ServiceTitlePredicate.java
  src/main/java/seedu/homerce/model/util/attributes/Date.java
  src/test/java/seedu/homerce/logic/commands/CommandTestUtil.java
  src/test/java/seedu/homerce/logic/commands/client/AddClientCommandTest.java
  src/test/java/seedu/homerce/logic/commands/client/FindClientCommandTest.java
  src/test/java/seedu/homerce/model/ModelManagerTest.java
  src/test/java/seedu/homerce/model/client/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/homerce/model/manager/ClientManagerTest.java
Labels: hacktoberfest-accepted, priority.High, type.Task

#152 Expense breakdown
  docs/UserGuide.md
  src/main/java/seedu/homerce/logic/commands/expense/AddExpenseCommand.java
  src/main/java/seedu/homerce/logic/commands/expense/BreakdownExpenseCommand.java
  src/main/java/seedu/homerce/logic/parser/HomerceParser.java
  src/main/java/seedu/homerce/logic/parser/ParserUtil.java
  src/main/java/seedu/homerce/logic/parser/expense/AddExpenseCommandParser.java
  src/main/java/seedu/homerce/logic/parser/expense/BreakdownExpenseCommandParser.java
  src/main/java/seedu/homerce/model/Model.java
  src/main/java/seedu/homerce/model/ModelManager.java
  src/main/java/seedu/homerce/model/util/attributes/Tag.java
Labels: hacktoberfest-accepted, priority.High

#151 Add undo feature
  src/main/java/seedu/homerce/MainApp.java
  src/main/java/seedu/homerce/logic/LogicManager.java
  src/main/java/seedu/homerce/logic/commands/Command.java
  src/main/java/seedu/homerce/logic/commands/ExitCommand.java
  src/main/java/seedu/homerce/logic/commands/HelpCommand.java
  src/main/java/seedu/homerce/logic/commands/ProfitCommand.java
  src/main/java/seedu/homerce/logic/commands/UndoCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/AddAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/ClearAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/DeleteAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/DoneAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/EditAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/FindAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/ListAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/UnDoneAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/client/AddClientCommand.java
  src/main/java/seedu/homerce/logic/commands/client/ClearClientCommand.java
  src/main/java/seedu/homerce/logic/commands/client/DeleteClientCommand.java
  src/main/java/seedu/homerce/logic/commands/client/EditClientCommand.java
  src/main/java/seedu/homerce/logic/commands/client/FindClientCommand.java
  src/main/java/seedu/homerce/logic/commands/client/ListClientCommand.java
  src/main/java/seedu/homerce/logic/commands/expense/AddExpenseCommand.java
  src/main/java/seedu/homerce/logic/commands/expense/ClearExpenseCommand.java
  src/main/java/seedu/homerce/logic/commands/expense/DeleteExpenseCommand.java
  src/main/java/seedu/homerce/logic/commands/expense/EditExpenseCommand.java
  src/main/java/seedu/homerce/logic/commands/expense/FindExpenseCommand.java
  src/main/java/seedu/homerce/logic/commands/expense/ListExpenseCommand.java
  src/main/java/seedu/homerce/logic/commands/revenue/AddRevenueCommand.java
  src/main/java/seedu/homerce/logic/commands/revenue/ClearRevenueCommand.java
  src/main/java/seedu/homerce/logic/commands/revenue/DeleteRevenueCommand.java
  src/main/java/seedu/homerce/logic/commands/revenue/FindRevenueCommand.java
  src/main/java/seedu/homerce/logic/commands/revenue/ListRevenueCommand.java
  src/main/java/seedu/homerce/logic/commands/service/AddServiceCommand.java
  src/main/java/seedu/homerce/logic/commands/service/ClearServiceCommand.java
  src/main/java/seedu/homerce/logic/commands/service/DeleteServiceCommand.java
  src/main/java/seedu/homerce/logic/commands/service/EditServiceCommand.java
  src/main/java/seedu/homerce/logic/commands/service/FindServiceCommand.java
  src/main/java/seedu/homerce/logic/commands/service/ListServiceCommand.java
  src/main/java/seedu/homerce/logic/parser/HomerceParser.java
  src/main/java/seedu/homerce/model/HistoryManager.java
  src/main/java/seedu/homerce/model/Model.java
  src/main/java/seedu/homerce/model/ModelManager.java
  src/main/java/seedu/homerce/model/client/UniqueClientList.java
  src/main/java/seedu/homerce/model/manager/AppointmentManager.java
  src/main/java/seedu/homerce/model/manager/ClientManager.java
  src/main/java/seedu/homerce/model/manager/ExpenseTracker.java
  src/main/java/seedu/homerce/model/manager/RevenueTracker.java
  src/main/java/seedu/homerce/model/manager/ServiceManager.java
  src/main/java/seedu/homerce/model/service/UniqueServiceList.java
  src/main/java/seedu/homerce/model/util/nonuniquelist/NonUniqueList.java
  src/main/java/seedu/homerce/model/util/uniquelist/UniqueList.java
  src/test/java/seedu/homerce/logic/LogicManagerTest.java
  src/test/java/seedu/homerce/logic/commands/CommandTestUtil.java
  src/test/java/seedu/homerce/logic/commands/client/AddClientCommandTest.java
Labels: priority.Medium, type.Story

#160 Homerce Icon, Tab Switching, Ui Enhancements
  copyright.txt
  src/main/java/seedu/homerce/commons/core/GuiSettings.java
  src/main/java/seedu/homerce/logic/commands/CommandResult.java
  src/main/java/seedu/homerce/logic/commands/appointment/AddAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/FindAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/ListAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/client/AddClientCommand.java
  src/main/java/seedu/homerce/logic/commands/client/FindClientCommand.java
  src/main/java/seedu/homerce/logic/commands/client/ListClientCommand.java
  src/main/java/seedu/homerce/logic/commands/expense/AddExpenseCommand.java
  src/main/java/seedu/homerce/logic/commands/expense/BreakdownExpenseCommand.java
  src/main/java/seedu/homerce/logic/commands/expense/FindExpenseCommand.java
  src/main/java/seedu/homerce/logic/commands/expense/ListExpenseCommand.java
  src/main/java/seedu/homerce/logic/commands/revenue/AddRevenueCommand.java
  src/main/java/seedu/homerce/logic/commands/revenue/FindRevenueCommand.java
  src/main/java/seedu/homerce/logic/commands/revenue/ListRevenueCommand.java
  src/main/java/seedu/homerce/logic/commands/service/AddServiceCommand.java
  src/main/java/seedu/homerce/logic/commands/service/FindServiceCommand.java
  src/main/java/seedu/homerce/logic/commands/service/ListServiceCommand.java
  src/main/java/seedu/homerce/ui/MainWindow.java
  src/main/java/seedu/homerce/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/homerce.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/SideTabsBar.fxml
  src/test/java/seedu/homerce/commons/util/AppUtilTest.java
Labels: priority.High, type.Task

#162 Refactor GrAB3 to Homerce
  docs/UserGuide.md
Labels: documentation, hacktoberfest-accepted, priority.Low

#169 Update UG
  docs/UserGuide.md
Labels: documentation, hacktoberfest-accepted, priority.High

#168 Improve Help command
  src/main/java/seedu/homerce/logic/commands/appointment/ClearAppointmentCommand.java
  src/main/java/seedu/homerce/ui/HelpWindow.java
  src/main/java/seedu/homerce/ui/MainWindow.java
  src/main/java/seedu/homerce/ui/UiManager.java
  src/main/resources/view/HelpWindow.fxml
Labels: priority.Medium, type.Enhancement

#173 Update UG
  docs/UserGuide.md
Labels: documentation, priority.High

#167 Apply Singleton design pattern
  src/main/java/seedu/homerce/MainApp.java
  src/main/java/seedu/homerce/logic/parser/ParserUtil.java
  src/main/java/seedu/homerce/model/HistoryManager.java
  src/test/java/seedu/homerce/logic/LogicManagerTest.java
  src/test/java/seedu/homerce/logic/commands/CommandTestUtil.java
  src/test/java/seedu/homerce/logic/commands/client/AddClientCommandTest.java
Labels: priority.Medium, type.Bug, type.Enhancement

#163 Done and Undone Commands will add/delete Revenue from Model
  src/main/java/seedu/homerce/commons/core/Messages.java
  src/main/java/seedu/homerce/logic/Logic.java
  src/main/java/seedu/homerce/logic/commands/appointment/AddAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/ClearAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/DeleteAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/DoneAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/EditAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/ListAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/UnDoneAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/client/AddClientCommand.java
  src/main/java/seedu/homerce/logic/commands/client/ClearClientCommand.java
  src/main/java/seedu/homerce/logic/commands/client/DeleteClientCommand.java
  src/main/java/seedu/homerce/logic/commands/client/EditClientCommand.java
  src/main/java/seedu/homerce/logic/commands/client/FindClientCommand.java
  src/main/java/seedu/homerce/logic/commands/client/ListClientCommand.java
  src/main/java/seedu/homerce/logic/commands/expense/FindExpenseCommand.java
  src/main/java/seedu/homerce/logic/commands/revenue/FindRevenueCommand.java
  src/main/java/seedu/homerce/logic/commands/service/ClearServiceCommand.java
  src/main/java/seedu/homerce/logic/parser/appointment/EditAppointmentCommandParser.java
  src/main/java/seedu/homerce/model/Model.java
  src/main/java/seedu/homerce/model/ModelManager.java
  src/main/java/seedu/homerce/model/appointment/Appointment.java
  src/main/java/seedu/homerce/model/client/Client.java
  src/main/java/seedu/homerce/model/client/Email.java
  src/main/java/seedu/homerce/model/client/Name.java
  src/main/java/seedu/homerce/model/client/Phone.java
  src/main/java/seedu/homerce/model/manager/AppointmentManager.java
  src/main/java/seedu/homerce/model/manager/ClientManager.java
  src/main/java/seedu/homerce/model/manager/ReadOnlyClientManager.java
  src/main/java/seedu/homerce/model/manager/ReadOnlyServiceManager.java
  src/main/java/seedu/homerce/model/util/attributes/Tag.java
  src/main/java/seedu/homerce/storage/client/JsonSerializableClientManager.java
  src/test/java/seedu/homerce/logic/commands/CommandTestUtil.java
  src/test/java/seedu/homerce/logic/commands/client/DeleteClientCommandTest.java
  src/test/java/seedu/homerce/logic/commands/client/EditClientCommandTest.java
Labels: priority.High, type.Enhancement

#176 DG v1.3
  docs/DeveloperGuide.md
Labels: documentation, hacktoberfest-accepted, priority.Medium

#177 Update UG for Appointment
  docs/UserGuide.md
  docs/images/helpMessage.png
Labels: documentation, priority.Medium

#185 Update UG for client commands
  build.gradle
  docs/UserGuide.md
Labels: documentation, priority.High

#181 Create schedule view for appointments
  src/main/java/seedu/homerce/logic/commands/appointment/AddAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/EditAppointmentCommand.java
  src/main/java/seedu/homerce/model/appointment/Appointment.java
  src/main/java/seedu/homerce/model/appointment/AppointmentTemp.java
  src/main/java/seedu/homerce/model/appointment/TimeOfDay.java
  src/main/java/seedu/homerce/model/appointment/uniquelist/AppointmentComparator.java
  src/main/java/seedu/homerce/model/util/attributes/Date.java
  src/main/java/seedu/homerce/storage/appointment/JsonAdaptedAppointment.java
  src/main/java/seedu/homerce/ui/MainWindow.java
  src/main/java/seedu/homerce/ui/SideTabsBar.java
  src/main/java/seedu/homerce/ui/appointmentpanel/AppointmentCard.java
  src/main/java/seedu/homerce/ui/schedulepanel/AppointmentSlot.java
  src/main/java/seedu/homerce/ui/schedulepanel/DisplayDateSlot.java
  src/main/java/seedu/homerce/ui/schedulepanel/SchedulePanel.java
  src/main/java/seedu/homerce/ui/schedulepanel/SlotContainer.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/SideTabsBar.fxml
  src/main/resources/view/schedulepanel/AppointmentSlot.fxml
  src/main/resources/view/schedulepanel/DisplayDateSlot.fxml
  src/main/resources/view/schedulepanel/SchedulePanel.fxml
  src/main/resources/view/stylesheets/default.css
Labels: priority.High, type.Enhancement, type.Task

#180 Recurring expense
  docs/UserGuide.md
  src/main/java/seedu/homerce/MainApp.java
  src/main/java/seedu/homerce/model/expense/IsFixed.java
  src/main/java/seedu/homerce/model/util/attributes/Date.java
  src/main/java/seedu/homerce/storage/expense/JsonAdaptedExpense.java
  src/main/java/seedu/homerce/storage/expense/JsonSerializableExpenseTracker.java
Labels: priority.High

#184 Undo feature enhancement
  src/main/java/seedu/homerce/MainApp.java
  src/main/java/seedu/homerce/logic/LogicManager.java
  src/main/java/seedu/homerce/logic/commands/Command.java
  src/main/java/seedu/homerce/logic/commands/ExitCommand.java
  src/main/java/seedu/homerce/logic/commands/HelpCommand.java
  src/main/java/seedu/homerce/logic/commands/ProfitCommand.java
  src/main/java/seedu/homerce/logic/commands/UndoCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/AddAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/ClearAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/DeleteAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/DoneAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/EditAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/FindAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/ListAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/UnDoneAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/client/AddClientCommand.java
  src/main/java/seedu/homerce/logic/commands/client/ClearClientCommand.java
  src/main/java/seedu/homerce/logic/commands/client/DeleteClientCommand.java
  src/main/java/seedu/homerce/logic/commands/client/EditClientCommand.java
  src/main/java/seedu/homerce/logic/commands/client/FindClientCommand.java
  src/main/java/seedu/homerce/logic/commands/client/ListClientCommand.java
  src/main/java/seedu/homerce/logic/commands/expense/AddExpenseCommand.java
  src/main/java/seedu/homerce/logic/commands/expense/BreakdownExpenseCommand.java
  src/main/java/seedu/homerce/logic/commands/expense/ClearExpenseCommand.java
  src/main/java/seedu/homerce/logic/commands/expense/DeleteExpenseCommand.java
  src/main/java/seedu/homerce/logic/commands/expense/EditExpenseCommand.java
  src/main/java/seedu/homerce/logic/commands/expense/FindExpenseCommand.java
  src/main/java/seedu/homerce/logic/commands/expense/ListExpenseCommand.java
  src/main/java/seedu/homerce/logic/commands/revenue/AddRevenueCommand.java
  src/main/java/seedu/homerce/logic/commands/revenue/ClearRevenueCommand.java
  src/main/java/seedu/homerce/logic/commands/revenue/DeleteRevenueCommand.java
  src/main/java/seedu/homerce/logic/commands/revenue/FindRevenueCommand.java
  src/main/java/seedu/homerce/logic/commands/revenue/ListRevenueCommand.java
  src/main/java/seedu/homerce/logic/commands/service/AddServiceCommand.java
  src/main/java/seedu/homerce/logic/commands/service/ClearServiceCommand.java
  src/main/java/seedu/homerce/logic/commands/service/DeleteServiceCommand.java
  src/main/java/seedu/homerce/logic/commands/service/EditServiceCommand.java
  src/main/java/seedu/homerce/logic/commands/service/FindServiceCommand.java
  src/main/java/seedu/homerce/logic/commands/service/ListServiceCommand.java
  src/main/java/seedu/homerce/model/manager/HistoryManager.java
  src/main/java/seedu/homerce/model/undo/History.java
  src/test/java/seedu/homerce/logic/LogicManagerTest.java
  src/test/java/seedu/homerce/logic/commands/CommandTestUtil.java
  src/test/java/seedu/homerce/logic/commands/client/AddClientCommandTest.java
Labels: priority.Medium, type.Task

#187 Breakdown Finance
  src/main/java/seedu/homerce/logic/.LogicManager.java.swp
  src/main/java/seedu/homerce/logic/commands/BreakdownFinanceCommand.java
  src/main/java/seedu/homerce/logic/commands/ProfitCommand.java
  src/main/java/seedu/homerce/logic/commands/expense/BreakdownExpenseCommand.java
  src/main/java/seedu/homerce/logic/parser/BreakdownFinanceCommandParser.java
  src/main/java/seedu/homerce/logic/parser/HomerceParser.java
  src/main/java/seedu/homerce/logic/parser/expense/BreakdownExpenseCommandParser.java
  src/main/java/seedu/homerce/model/expense/predicate/ExpenseMonthPredicate.java
  src/main/java/seedu/homerce/model/expense/predicate/ExpenseMonthYearPredicate.java
  src/main/java/seedu/homerce/model/expense/predicate/ExpenseYearPredicate.java
  src/main/java/seedu/homerce/model/revenue/predicate/RevenueMonthPredicate.java
  src/main/java/seedu/homerce/model/revenue/predicate/RevenueMonthYearPredicate.java
  src/main/java/seedu/homerce/model/revenue/predicate/RevenueYearPredicate.java
Labels: priority.High

#191 Implement Expense Sort Feature
  src/main/java/seedu/homerce/logic/commands/expense/ListExpenseCommand.java
  src/main/java/seedu/homerce/logic/commands/expense/SortExpenseCommand.java
  src/main/java/seedu/homerce/logic/parser/HomerceParser.java
  src/main/java/seedu/homerce/logic/parser/ParserUtil.java
  src/main/java/seedu/homerce/logic/parser/expense/SortExpenseCommandParser.java
  src/main/java/seedu/homerce/model/ModelManager.java
  src/main/java/seedu/homerce/model/expense/ExpenseComparator.java
  src/main/java/seedu/homerce/model/expense/ExpenseDefaultComparator.java
  src/main/java/seedu/homerce/model/manager/ExpenseTracker.java
  src/main/java/seedu/homerce/model/manager/ReadOnlyExpenseTracker.java
  src/main/java/seedu/homerce/model/util/nonuniquelist/NonUniqueList.java
Labels: priority.Medium

#190 Service list ordering
  src/main/java/seedu/homerce/logic/.LogicManager.java.swp
  src/main/java/seedu/homerce/model/service/ServiceCode.java
  src/main/java/seedu/homerce/model/service/ServiceComparator.java
  src/main/java/seedu/homerce/model/service/UniqueServiceList.java
Labels: priority.Medium, type.Enhancement

#189 UI for breakdownfinance
  ArchitectureDiagram.png
  ArchitectureSequenceDiagram.png
  src/main/java/seedu/homerce/logic/commands/BreakdownFinanceCommand.java
  src/main/java/seedu/homerce/logic/commands/CommandResult.java
  src/main/java/seedu/homerce/logic/commands/ExitCommand.java
  src/main/java/seedu/homerce/logic/commands/HelpCommand.java
  src/main/java/seedu/homerce/ui/MainWindow.java
  src/main/java/seedu/homerce/ui/financialpanel/FinanceWindow.java
  src/main/resources/view/financialpanel/BreakdownFinancial.fxml
  src/main/resources/view/financialpanel/style.css
  src/test/java/seedu/homerce/logic/commands/CommandResultTest.java
  src/test/java/seedu/homerce/logic/commands/ExitCommandTest.java
  src/test/java/seedu/homerce/logic/commands/HelpCommandTest.java
Labels: priority.High, type.Story

#200 Pagination Feature for Schedule View
  src/main/java/seedu/homerce/logic/Logic.java
  src/main/java/seedu/homerce/logic/LogicManager.java
  src/main/java/seedu/homerce/logic/commands/appointment/AddAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/ClearAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/DeleteAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/DoneAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/EditAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/UnDoneAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/schedule/AbstractWeekCommand.java
  src/main/java/seedu/homerce/logic/commands/schedule/CurrentWeekCommand.java
  src/main/java/seedu/homerce/logic/commands/schedule/CustomWeekCommand.java
  src/main/java/seedu/homerce/logic/commands/schedule/NextWeekCommand.java
  src/main/java/seedu/homerce/logic/commands/schedule/PreviousWeekCommand.java
  src/main/java/seedu/homerce/logic/parser/HomerceParser.java
  src/main/java/seedu/homerce/logic/parser/appointment/FindAppointmentCommandParser.java
  src/main/java/seedu/homerce/logic/parser/schedule/ScheduleCommandParser.java
  src/main/java/seedu/homerce/model/Model.java
  src/main/java/seedu/homerce/model/ModelManager.java
  src/main/java/seedu/homerce/model/appointment/predicate/AppointmentPaginationPredicate.java
  src/main/java/seedu/homerce/model/manager/AppointmentManager.java
  src/main/java/seedu/homerce/model/manager/ReadOnlyAppointmentManager.java
  src/main/java/seedu/homerce/ui/HelpWindow.java
  src/main/java/seedu/homerce/ui/MainWindow.java
  src/main/resources/view/HelpWindow.fxml
  src/test/java/seedu/homerce/logic/commands/client/AddClientCommandTest.java
Labels: priority.High, type.Story

#203 Add tests for expense
  src/main/java/seedu/homerce/logic/commands/expense/AddExpenseCommand.java
  src/main/java/seedu/homerce/model/expense/Expense.java
  src/main/java/seedu/homerce/model/expense/IsFixed.java
  src/test/java/seedu/homerce/logic/commands/client/AddClientCommandTest.java
  src/test/java/seedu/homerce/logic/commands/expense/AddExpenseCommandTest.java
  src/test/java/seedu/homerce/logic/commands/expense/ClearExpenseCommandTest.java
  src/test/java/seedu/homerce/logic/commands/expense/DeleteExpenseCommandTest.java
  src/test/java/seedu/homerce/logic/commands/expense/EditExpenseCommandTest.java
  src/test/java/seedu/homerce/logic/commands/expense/ExpenseCommandTestUtil.java
  src/test/java/seedu/homerce/model/NonUniqueListTest.java
  src/test/java/seedu/homerce/model/expense/ExpenseComparatorTest.java
  src/test/java/seedu/homerce/model/expense/ExpenseDatePredicateTest.java
  src/test/java/seedu/homerce/model/expense/ExpenseDefaultComparatorTest.java
  src/test/java/seedu/homerce/model/expense/ExpenseDescriptionPredicateTest.java
  src/test/java/seedu/homerce/model/expense/ExpenseIsFixedPredicateTest.java
  src/test/java/seedu/homerce/model/expense/ExpenseMonthYearPredicateTest.java
  src/test/java/seedu/homerce/model/expense/ExpenseTest.java
  src/test/java/seedu/homerce/model/expense/IsFixedTest.java
  src/test/java/seedu/homerce/model/expense/TagPredicateTest.java
  src/test/java/seedu/homerce/testutil/expense/EditExpenseDescriptorBuilder.java
  src/test/java/seedu/homerce/testutil/expense/ExpenseBuilder.java
  src/test/java/seedu/homerce/testutil/expense/ExpenseTrackerBuilder.java
  src/test/java/seedu/homerce/testutil/expense/TypicalExpenseIndexes.java
  src/test/java/seedu/homerce/testutil/expense/TypicalExpenses.java
Labels: priority.High, type:Testing

#194 Sort Revenue Feature
  src/main/java/seedu/homerce/logic/commands/revenue/ListRevenueCommand.java
  src/main/java/seedu/homerce/logic/commands/revenue/SortRevenueCommand.java
  src/main/java/seedu/homerce/logic/parser/HomerceParser.java
  src/main/java/seedu/homerce/logic/parser/ParserUtil.java
  src/main/java/seedu/homerce/logic/parser/revenue/SortRevenueCommandParser.java
  src/main/java/seedu/homerce/model/ModelManager.java
  src/main/java/seedu/homerce/model/manager/ReadOnlyRevenueTracker.java
  src/main/java/seedu/homerce/model/manager/RevenueTracker.java
  src/main/java/seedu/homerce/model/revenue/RevenueComparator.java
  src/main/java/seedu/homerce/model/revenue/RevenueDefaultComparator.java
Labels: hacktoberfest-accepted, priority.High, type.Enhancement

#207 Add tests for client
  src/main/java/seedu/homerce/commons/core/Messages.java
  src/main/java/seedu/homerce/logic/parser/client/FindClientCommandParser.java
  src/main/java/seedu/homerce/model/client/UniqueClientList.java
  src/main/java/seedu/homerce/model/manager/ClientManager.java
  src/test/java/seedu/homerce/logic/parser/client/FindClientCommandParserTest.java
  src/test/java/seedu/homerce/model/client/ClientTest.java
  src/test/java/seedu/homerce/model/client/UniqueClientListTest.java
  src/test/java/seedu/homerce/model/client/predicate/ClientNamePredicateTest.java
  src/test/java/seedu/homerce/model/client/predicate/ClientPhonePredicateTest.java
  src/test/java/seedu/homerce/model/client/predicate/NameContainsKeywordsPredicateTest.java
Labels: priority.High, type:Testing

#205 Refactor use case formatting
  docs/DeveloperGuide.md
Labels: documentation, priority.Low

#212 Add tests for expense (storage, parser)
  README.md
  src/main/java/seedu/homerce/logic/commands/expense/AddExpenseCommand.java
  src/main/java/seedu/homerce/logic/commands/expense/DeleteExpenseCommand.java
  src/main/java/seedu/homerce/logic/commands/expense/EditExpenseCommand.java
  src/main/java/seedu/homerce/logic/commands/expense/FindExpenseCommand.java
  src/main/java/seedu/homerce/logic/commands/expense/SortExpenseCommand.java
  src/main/java/seedu/homerce/storage/expense/JsonAdaptedExpense.java
  src/main/java/seedu/homerce/storage/expense/JsonSerializableExpenseTracker.java
  src/test/data/Expense/JsonExpenseStorageTest/invalidAndValidExpenseTracker.json
  src/test/data/Expense/JsonExpenseStorageTest/invalidExpenseTracker.json
  src/test/data/Expense/JsonExpenseStorageTest/notJsonFormatExpense.json
  src/test/data/Expense/JsonSerializableExpenseTrackerTest/invalidExpenseTracker.json
  src/test/data/Expense/JsonSerializableExpenseTrackerTest/typicalExpenseTracker.json
  src/test/java/seedu/homerce/logic/commands/expense/DeleteExpenseCommandTest.java
  src/test/java/seedu/homerce/logic/commands/expense/EditExpenseCommandTest.java
  src/test/java/seedu/homerce/logic/commands/expense/ExpenseCommandTestUtil.java
  src/test/java/seedu/homerce/logic/commands/expense/FindExpenseCommandTest.java
  src/test/java/seedu/homerce/logic/commands/expense/ListExpenseCommandTest.java
  src/test/java/seedu/homerce/logic/commands/expense/SortExpenseCommandTest.java
  src/test/java/seedu/homerce/logic/parser/expense/AddExpenseCommandParserTest.java
  src/test/java/seedu/homerce/logic/parser/expense/DeleteExpenseCommandParserTest.java
  src/test/java/seedu/homerce/logic/parser/expense/EditExpenseCommandParserTest.java
  src/test/java/seedu/homerce/logic/parser/expense/FindExpenseCommandParserTest.java
  src/test/java/seedu/homerce/logic/parser/expense/SortExpenseCommandParserTest.java
  src/test/java/seedu/homerce/model/expense/ExpenseDatePredicateTest.java
  src/test/java/seedu/homerce/model/expense/ExpenseMonthYearPredicateTest.java
  src/test/java/seedu/homerce/model/expense/ExpenseTest.java
  src/test/java/seedu/homerce/storage/expense/JsonAdaptedExpenseTest.java
  src/test/java/seedu/homerce/storage/expense/JsonExpenseStorageTest.java
  src/test/java/seedu/homerce/storage/expense/JsonSerializableExpenseTrackerTest.java
  src/test/java/seedu/homerce/testutil/expense/ExpenseBuilder.java
  src/test/java/seedu/homerce/testutil/expense/TypicalExpenses.java
  src/test/java/seedu/homerce/testutil/revenue/RevenueBuilder.java
Labels: priority.High, type:Testing

#214 Enhanced UI for homerece
  src/main/java/seedu/homerce/model/util/SampleDataUtil.java
  src/main/java/seedu/homerce/ui/schedulepanel/AppointmentSlot.java
  src/main/java/seedu/homerce/ui/schedulepanel/DisplayDateSlot.java
  src/main/resources/images/appointments.png
  src/main/resources/images/clients.png
  src/main/resources/images/expenses.png
  src/main/resources/images/revenue.png
  src/main/resources/images/schedule.png
  src/main/resources/images/services.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/SideTabsBar.fxml
  src/main/resources/view/financialpanel/BreakdownFinancial.fxml
  src/main/resources/view/schedulepanel/AppointmentSlot.fxml
  src/main/resources/view/schedulepanel/DisplayDateSlot.fxml
  src/main/resources/view/schedulepanel/SchedulePanel.fxml
Labels: priority.Medium, type.Enhancement

#202 Add condition for deletion of service
  src/main/java/seedu/homerce/commons/core/Messages.java
  src/main/java/seedu/homerce/logic/commands/service/DeleteServiceCommand.java
Labels: priority.High, type.Bug

#211 Update UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation, priority.High

#215 Update UG
  docs/UserGuide.md
Labels: documentation, priority.Medium

#217 Tests for Appointment (Model)
  docs/UserGuide.md
  src/main/java/seedu/homerce/logic/commands/schedule/CustomWeekCommand.java
  src/main/java/seedu/homerce/model/ModelManager.java
  src/main/java/seedu/homerce/model/appointment/Appointment.java
  src/main/java/seedu/homerce/model/appointment/TimeOfDay.java
  src/main/java/seedu/homerce/model/appointment/exceptions/AppointmentNotFoundException.java
  src/main/java/seedu/homerce/model/appointment/predicate/AppointmentWeekPredicate.java
  src/main/java/seedu/homerce/model/manager/AppointmentManager.java
  src/main/java/seedu/homerce/ui/schedulepanel/AppointmentSlot.java
  src/test/java/seedu/homerce/logic/LogicManagerTest.java
  src/test/java/seedu/homerce/logic/commands/CommandTestUtil.java
  src/test/java/seedu/homerce/logic/commands/client/AddClientCommandIntegrationTest.java
  src/test/java/seedu/homerce/logic/commands/client/AddClientCommandTest.java
  src/test/java/seedu/homerce/logic/commands/client/ClearClientCommandTest.java
  src/test/java/seedu/homerce/logic/commands/client/DeleteClientCommandTest.java
  src/test/java/seedu/homerce/logic/commands/client/EditClientCommandTest.java
  src/test/java/seedu/homerce/logic/commands/client/EditClientDescriptorTest.java
  src/test/java/seedu/homerce/logic/commands/client/FindClientCommandTest.java
  src/test/java/seedu/homerce/logic/commands/client/ListClientCommandTest.java
  src/test/java/seedu/homerce/logic/parser/ClientManagerParserTest.java
  src/test/java/seedu/homerce/logic/parser/client/AddClientCommandParserTest.java
  src/test/java/seedu/homerce/logic/parser/client/EditClientCommandParserTest.java
  src/test/java/seedu/homerce/model/ModelManagerTest.java
  src/test/java/seedu/homerce/model/appointment/AppointmentTempTest.java
  src/test/java/seedu/homerce/model/appointment/AppointmentTest.java
  src/test/java/seedu/homerce/model/appointment/TimeOfDayTest.java
  src/test/java/seedu/homerce/model/appointment/TypicalAppointments.java
  src/test/java/seedu/homerce/model/appointment/predicate/AppointmentDatePredicateTest.java
  src/test/java/seedu/homerce/model/appointment/predicate/AppointmentNamePredicateTest.java
  src/test/java/seedu/homerce/model/appointment/predicate/AppointmentPhonePredicateTest.java
  src/test/java/seedu/homerce/model/appointment/predicate/AppointmentServiceCodePredicateTest.java
  src/test/java/seedu/homerce/model/appointment/predicate/AppointmentWeekPredicateTest.java
  src/test/java/seedu/homerce/model/appointment/uniquelist/AppointmentComparatorTest.java
  src/test/java/seedu/homerce/model/appointment/uniquelist/UniqueAppointmentListTest.java
  src/test/java/seedu/homerce/model/client/ClientTest.java
  src/test/java/seedu/homerce/model/client/UniqueClientListTest.java
  src/test/java/seedu/homerce/model/client/predicate/ClientNamePredicateTest.java
  src/test/java/seedu/homerce/model/client/predicate/ClientPhonePredicateTest.java
  src/test/java/seedu/homerce/model/client/predicate/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/homerce/model/manager/AppointmentManagerTest.java
  src/test/java/seedu/homerce/model/manager/ClientManagerTest.java
  src/test/java/seedu/homerce/storage/StorageManagerTest.java
  src/test/java/seedu/homerce/storage/client/JsonAdaptedClientTest.java
  src/test/java/seedu/homerce/storage/client/JsonClientStorageTest.java
  src/test/java/seedu/homerce/storage/client/JsonSerializableClientManagerTest.java
  src/test/java/seedu/homerce/testutil/appointment/AppointmentBuilder.java
  src/test/java/seedu/homerce/testutil/appointment/TypicalAppointments.java
  src/test/java/seedu/homerce/testutil/client/ClientBuilder.java
  src/test/java/seedu/homerce/testutil/client/ClientManagerBuilder.java
  src/test/java/seedu/homerce/testutil/client/ClientUtil.java
  src/test/java/seedu/homerce/testutil/client/EditClientDescriptorBuilder.java
  src/test/java/seedu/homerce/testutil/client/TypicalClients.java
Labels: priority.Medium, type:Testing

#219 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/service/AddServiceActivityDiagram.puml
  docs/diagrams/service/AddServiceSequenceDiagram.puml
  docs/images/AddServiceActivityDiagram.png
  docs/images/AddServiceSequenceDiagram.png
Labels: documentation, priority.High

#228 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/expense/SortExpenseActivityDiagram.puml
  docs/diagrams/expense/SortExpenseSD.puml
  docs/diagrams/service/AddServiceActivityDiagram.puml
  docs/images/SortExpenseActivityDiagram.png
  docs/images/SortExpenseSD.png
  src/main/java/seedu/homerce/ui/appointmentpanel/AppointmentCard.java
  src/main/java/seedu/homerce/ui/expensepanel/ExpenseCard.java
  src/main/java/seedu/homerce/ui/schedulepanel/SchedulePanel.java
  src/main/java/seedu/homerce/ui/servicepanel/ServiceCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/appointmentpanel/AppointmentListCard.fxml
  src/main/resources/view/expensepanel/ExpenseListCard.fxml
  src/main/resources/view/schedulepanel/DisplayDateSlot.fxml
  src/main/resources/view/servicepanel/ServiceListCard.fxml
Labels: documentation

#226 Update DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/financebreakdown/BreakdownFinanceActivityDiagram.puml
  docs/diagrams/financebreakdown/BreakdownFinanceSequenceDiagram.puml
  docs/images/BreakdownFinanceActivityDiagram.png
  docs/images/BreakdownFinanceSequenceDiagram.png
Labels: documentation, priority.High

#230 Enhance Schedule UI
  src/main/java/seedu/homerce/logic/Logic.java
  src/main/java/seedu/homerce/logic/LogicManager.java
  src/main/java/seedu/homerce/model/appointment/predicate/AppointmentWeekPredicate.java
  src/main/java/seedu/homerce/model/manager/AppointmentManager.java
  src/main/java/seedu/homerce/model/manager/ReadOnlyAppointmentManager.java
  src/main/java/seedu/homerce/ui/MainWindow.java
  src/main/java/seedu/homerce/ui/schedulepanel/SchedulePanel.java
  src/main/resources/view/DarkTheme.css
  src/test/java/seedu/homerce/model/manager/AppointmentManagerTest.java
Labels: priority.Medium, type.Enhancement

#232 Update UG
  docs/UserGuide.md
Labels: documentation

#233 Update UG and DG for expense
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#234 Update UG GUI
  docs/UserGuide.md
  docs/images/AnnotatedUI.png
  docs/images/Ui.png
Labels: documentation

#236 Units Tests for Appointment (Logic and Storage)
  src/main/java/seedu/homerce/logic/commands/appointment/DeleteAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/DoneAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/FindAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/ListAppointmentCommand.java
  src/main/java/seedu/homerce/logic/commands/appointment/UnDoneAppointmentCommand.java
  src/main/java/seedu/homerce/logic/parser/appointment/FindAppointmentCommandParser.java
  src/main/java/seedu/homerce/model/ModelManager.java
  src/main/java/seedu/homerce/model/appointment/Appointment.java
  src/main/java/seedu/homerce/model/appointment/AppointmentTemp.java
  src/main/java/seedu/homerce/model/service/ServiceCode.java
  src/main/java/seedu/homerce/storage/appointment/JsonAdaptedAppointment.java
  src/test/data/Appointment/JsonAppointmentStorageTest/invalidAndValidAppointmentManager.json
  src/test/data/Appointment/JsonAppointmentStorageTest/invalidAppointmentManager.json
  src/test/data/Appointment/JsonAppointmentStorageTest/notJsonFormatAppointment.json
  src/test/data/Appointment/JsonSerializableAppointmentManagerTest/duplicateAppointment.json
  src/test/data/Appointment/JsonSerializableAppointmentManagerTest/invalidAppointmentManager.json
  src/test/data/Appointment/JsonSerializableAppointmentManagerTest/typicalAppointmentManager.json
  src/test/java/seedu/homerce/logic/commands/appointment/AddAppointmentCommandTest.java
  src/test/java/seedu/homerce/logic/commands/appointment/ClearAppointmentCommandTest.java
  src/test/java/seedu/homerce/logic/commands/appointment/DeleteAppointmentCommandTest.java
  src/test/java/seedu/homerce/logic/commands/appointment/DoneAppointmentCommandTest.java
  src/test/java/seedu/homerce/logic/commands/appointment/EditAppointmentCommandTest.java
  src/test/java/seedu/homerce/logic/commands/appointment/FindAppointmentCommandTest.java
  src/test/java/seedu/homerce/logic/commands/appointment/ListAppointmentCommandTest.java
  src/test/java/seedu/homerce/logic/commands/appointment/UnDoneAppointmentCommandTest.java
  src/test/java/seedu/homerce/logic/commands/client/DeleteClientCommandTest.java
  src/test/java/seedu/homerce/logic/commands/revenue/ListRevenueCommandTest.java
  src/test/java/seedu/homerce/logic/parser/appointment/AddAppointmentCommandParserTest.java
  src/test/java/seedu/homerce/logic/parser/appointment/DeleteAppointmentCommandParserTest.java
  src/test/java/seedu/homerce/logic/parser/appointment/DoneAppointmentCommandParserTest.java
  src/test/java/seedu/homerce/logic/parser/appointment/EditAppointmentCommandParserTest.java
  src/test/java/seedu/homerce/logic/parser/appointment/FindAppointmentCommandParserTest.java
  src/test/java/seedu/homerce/logic/parser/appointment/UnDoneAppointmentCommandParserTest.java
  src/test/java/seedu/homerce/model/appointment/AppointmentTempTest.java
  src/test/java/seedu/homerce/model/appointment/AppointmentTest.java
  src/test/java/seedu/homerce/model/service/ServiceCodeTest.java
  src/test/java/seedu/homerce/storage/appointment/JsonAdaptedAppointmentTest.java
  src/test/java/seedu/homerce/storage/appointment/JsonAppointmentStorageTest.java
  src/test/java/seedu/homerce/storage/appointment/JsonSerializableAppointmentManagerTest.java
  src/test/java/seedu/homerce/testutil/appointment/AppointmentTempBuilder.java
  src/test/java/seedu/homerce/testutil/appointment/EditAppointmentDescriptorBuilder.java
  src/test/java/seedu/homerce/testutil/appointment/TypicalAppointmentIndexes.java
  src/test/java/seedu/homerce/testutil/appointment/TypicalAppointments.java
Labels: priority.Medium, type:Testing

#225 Add more tests for service
  src/main/java/seedu/homerce/logic/commands/client/EditClientCommand.java
  src/main/java/seedu/homerce/logic/commands/service/AddServiceCommand.java
  src/main/java/seedu/homerce/logic/commands/service/EditServiceCommand.java
  src/test/data/Service/JsonSerializableServiceManagerTest/duplicateService.json
  src/test/data/Service/JsonSerializableServiceManagerTest/invalidServiceManager.json
  src/test/data/Service/JsonSerializableServiceManagerTest/typicalServiceManager.json
  src/test/data/Service/JsonServiceStorageTest/invalidAndValidServiceManager.json
  src/test/data/Service/JsonServiceStorageTest/invalidServiceManager.json
  src/test/data/Service/JsonServiceStorageTest/notJsonFormatService.json
  src/test/java/seedu/homerce/logic/commands/CommandTestUtil.java
  src/test/java/seedu/homerce/logic/commands/revenue/AddRevenueCommandTest.java
  src/test/java/seedu/homerce/logic/commands/revenue/DeleteRevenueCommandTest.java
  src/test/java/seedu/homerce/logic/commands/service/AddServiceCommandIntegrationTest.java
  src/test/java/seedu/homerce/logic/commands/service/AddServiceCommandTest.java
  src/test/java/seedu/homerce/logic/commands/service/ClearServiceCommandTest.java
  src/test/java/seedu/homerce/logic/commands/service/DeleteServiceCommandTest.java
  src/test/java/seedu/homerce/logic/commands/service/EditServiceCommandTest.java
  src/test/java/seedu/homerce/logic/commands/service/EditServiceDescriptorTest.java
  src/test/java/seedu/homerce/logic/commands/service/FindServiceCommandTest.java
  src/test/java/seedu/homerce/logic/commands/service/ListServiceCommandTest.java
  src/test/java/seedu/homerce/logic/parser/service/AddServiceCommandParserTest.java
  src/test/java/seedu/homerce/logic/parser/service/DeleteServiceCommandParserTest.java
  src/test/java/seedu/homerce/logic/parser/service/EditServiceCommandParserTest.java
  src/test/java/seedu/homerce/logic/parser/service/FindExpenseCommandParserTest.java
  src/test/java/seedu/homerce/model/service/ServiceTest.java
  src/test/java/seedu/homerce/storage/service/JsonAdaptedServiceTest.java
  src/test/java/seedu/homerce/storage/service/JsonSerializableServiceManagerTest.java
  src/test/java/seedu/homerce/storage/service/JsonServiceStorageTest.java
  src/test/java/seedu/homerce/testutil/TypicalIndexes.java
  src/test/java/seedu/homerce/testutil/service/EditServiceDescriptorBuilder.java
  src/test/java/seedu/homerce/testutil/service/TypicalServices.java
Labels: priority.High, type:Testing

#291 Branch fix ug bugs
  docs/UserGuide.md
Labels: priority.High, type.Bug
